version: '3.7'
services:
  postgres:
    container_name: pg_db
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/latest
    networks:
      - postgres_network
    ports:
      - 5432:5432
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres_network
    links:
      - "postgres:db"
    ports:
      - 8080:80
volumes:
  postgres:
  pgadmin:
networks:
  postgres_network:
    driver: bridge