version: '3.7'
services:
  postgres:
    container_name: pg_db
    image: postgres
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_USER='admin'
      - POSTGRES_PASSWORD='admin'
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/data/postgres
    networks:
      - postgres
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL='admin@admin.com'
      - PGADMIN_DEFAULT_PASSWORD='password'
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - postgres
    ports:
      - 8080:80
volumes:
  postgres:
  pgadmin:
networks:
  postgres:
    driver: bridge