version: '3.7'
services:
  postgres:
    container_name: pg_db
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gateway
      - POSTGRES_HOST_AUTH_METHOD=trust # NOT recommended for anything other than local/dev environments - this disables the need for using your password!
      - PGDATA=/var/lib/postgresql/data/latest
    networks:
      - postgres_network
    ports:
      - 5432:5432
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com # this is used to sign in to the pgadmin console
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres_network
    links:
      - "postgres:db" # you can use 'db' as the hostname when connecting to postgres from your pgadmin UI
    ports:
      - 8080:80 # will make the UI run on localhost:8080
volumes:
  postgres:
  pgadmin:
networks:
  postgres_network:
    driver: bridge