services:
  zoo:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-network
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zoo
    links:
      - zoo
    ports:
      - "9092:9092"

networks:
  kafka-network:
    driver: bridge